/*
 * TTSGui.java
 *
 * Created on 26. Mai 2010, 09:36
 */

package eu.semaine.components.dummy;

import eu.semaine.system.CharacterConfigInfo;

/**
 *
 * @author  marc
 */
public class TTSGui extends javax.swing.JFrame {
    private TTSInputComponent component;
    private CharacterConfigInfo currentCharacter;
    
    /** Creates new form TTSGui */
    public TTSGui(TTSInputComponent component) {
        this.component = component;
        initComponents();
        initCharacters();
    }
    
    private void initCharacters() {
        cbCharacter.removeAllItems();
        for (String character : CharacterConfigInfo.getCharacterNames()) {
            // We want to avoid sending context messages while filling the combobox;
            // therefore we always fill currentSelection with the item of choice.
            currentCharacter = CharacterConfigInfo.getInfo(character);
            cbCharacter.addItem(currentCharacter);
        }
        // Now we do want to send a message:
        currentCharacter = null;
        cbCharacter.setSelectedItem(CharacterConfigInfo.getDefaultCharacter());
    }
    
    public String getText() {
        return taText.getText();
    }
    
    public String getLocaleString() {
        return ((CharacterConfigInfo)cbCharacter.getSelectedItem()).getVoiceLocaleString();
    }
    
    public String getCharacterName() {
        return ((CharacterConfigInfo) cbCharacter.getSelectedItem()).getName();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        bSpeak = new javax.swing.JButton();
        cbCharacter = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        taText.setColumns(20);
        taText.setRows(5);
        taText.setText("Put text to be spoken here.");
        jScrollPane1.setViewportView(taText);

        jLabel2.setText("Character:");

        bSpeak.setText("Speak");
        bSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSpeakActionPerformed(evt);
            }
        });

        cbCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCharacterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCharacter, 0, 534, Short.MAX_VALUE))
                    .addComponent(bSpeak))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSpeak))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCharacterActionPerformed
        CharacterConfigInfo cci = (CharacterConfigInfo) cbCharacter.getSelectedItem();
        if (cci != currentCharacter) {
            component.setCharacter(cci.getName());
            currentCharacter = cci;
            
        }
    }//GEN-LAST:event_cbCharacterActionPerformed

    public void updateCharacterDisplay(String newCharacterName) {
        for (int i=0, max = cbCharacter.getItemCount(); i<max; i++) {
            CharacterConfigInfo cci = (CharacterConfigInfo) cbCharacter.getItemAt(i);
            if (cci.getName().equals(newCharacterName)) {
                // We want to update the display without sending a context message:
                currentCharacter = cci;
                cbCharacter.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void bSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpeakActionPerformed
        component.speak(getText(), getLocaleString());
    }//GEN-LAST:event_bSpeakActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSpeak;
    private javax.swing.JComboBox cbCharacter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taText;
    // End of variables declaration//GEN-END:variables
    
}
