/*
 * UtterancePreparationTestGUI.java
 *
 * Created on 24. Juni 2010, 15:08
 */

package eu.semaine.components.dummy;

import eu.semaine.components.dummy.UtterancePreparationTestComponent.Action;
/**
 *
 * @author  marc
 */
public class UtterancePreparationTestGUI extends javax.swing.JFrame {
    private UtterancePreparationTestComponent comp;
    
    /** Creates new form UtterancePreparationTestGUI */
    public UtterancePreparationTestGUI(UtterancePreparationTestComponent comp) {
        this.comp = comp;
        initComponents();
        verifyButtonsEnabled();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        contentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lUtterances = new javax.swing.JList();
        buttonPanel = new javax.swing.JPanel();
        bPrepare = new javax.swing.JButton();
        bPlayPrepared = new javax.swing.JButton();
        bPlayDirect = new javax.swing.JButton();
        bPlay = new javax.swing.JButton();
        logPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(400, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(500, 400));
        contentPanel.setLayout(new java.awt.BorderLayout());

        lUtterances.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "This is the first utterance.", "And a second utterance.", "Utterance number three, believe it or not.", "Four makes a square.", "Five fingers to a hand.", "Six pack, where are you?", "Seven days, every single week.", "Number eight, black and round.", "Nine means no in German.", "Ten, I'm a fan.", "Eleven, like in heaven.", "Twelve, a full dozen, and that must be enough." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lUtterances.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lUtterances.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lUtterancesValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(lUtterances);

        contentPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        bPrepare.setText("Prepare");
        bPrepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrepareActionPerformed(evt);
            }
        });

        buttonPanel.add(bPrepare);

        bPlayPrepared.setText("PlayPrepared");
        bPlayPrepared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayPreparedActionPerformed(evt);
            }
        });

        buttonPanel.add(bPlayPrepared);

        bPlayDirect.setText("PlayDirect");
        bPlayDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayDirectActionPerformed(evt);
            }
        });

        buttonPanel.add(bPlayDirect);

        bPlay.setText("Play");
        bPlay.setToolTipText("Play prepared if available, or direct if not available");
        bPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayActionPerformed(evt);
            }
        });

        buttonPanel.add(bPlay);

        contentPanel.add(buttonPanel, java.awt.BorderLayout.EAST);

        jSplitPane1.setTopComponent(contentPanel);

        logPanel.setLayout(new java.awt.BorderLayout());

        taLog.setColumns(20);
        taLog.setRows(5);
        taLog.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(taLog);

        logPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(logPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lUtterancesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lUtterancesValueChanged
        verifyButtonsEnabled();
    }//GEN-LAST:event_lUtterancesValueChanged

    private void bPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayActionPerformed
        String id = getSelectedItemID();
        String text = getSelectedItemText();
        if (id != null) {
            comp.triggerAction(Action.Play, text, id);
        }
    }//GEN-LAST:event_bPlayActionPerformed

    private void bPlayDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayDirectActionPerformed
        String id = getSelectedItemID();
        String text = getSelectedItemText();
        if (id != null) {
            comp.triggerAction(Action.PlayDirect, text, id);
        }
    }//GEN-LAST:event_bPlayDirectActionPerformed

    private void bPlayPreparedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayPreparedActionPerformed
        String id = getSelectedItemID();
        String text = getSelectedItemText();
        if (id != null) {
            comp.triggerAction(Action.PlayPrepared, text, id);
        }
    }//GEN-LAST:event_bPlayPreparedActionPerformed

    private void bPrepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrepareActionPerformed
        String id = getSelectedItemID();
        String text = getSelectedItemText();
        if (id != null) {
            comp.triggerAction(Action.Prepare, text, id);
        }
    }//GEN-LAST:event_bPrepareActionPerformed
    
    public void log(String s) {
        taLog.append(s+"\n");
        taLog.setCaretPosition(taLog.getDocument().getLength());
    }
    
    private String getSelectedItemID() {
        int index = lUtterances.getSelectedIndex();
        if (index == -1) {
            return null;
        }
        return "item"+(index+1);
    }

    private String getSelectedItemText() {
        int index = lUtterances.getSelectedIndex();
        if (index == -1) {
            return null;
        }
        return lUtterances.getSelectedValue().toString();
    }

    public void verifyButtonsEnabled() {
        String id = getSelectedItemID();
        if (id == null) {
            bPrepare.setEnabled(false);
            bPlayPrepared.setEnabled(false);
            bPlayDirect.setEnabled(false);
            bPlay.setEnabled(false);
        } else {
            boolean idReady = comp.isReady(id);
            bPrepare.setEnabled(!idReady);
            bPlayPrepared.setEnabled(idReady);
            bPlayDirect.setEnabled(true);
            bPlay.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bPlayDirect;
    private javax.swing.JButton bPlayPrepared;
    private javax.swing.JButton bPrepare;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList lUtterances;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea taLog;
    // End of variables declaration//GEN-END:variables
    
}
