//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : schedulerElement.h
//  @ Date : 22/07/2008
//  @ Author : 
//
//
#pragma once

#if !defined(AGENTBEHAVIOUR_H)
#define _AGENTBEHAVIOUR_H

#include <string>
#include <algorithm>


class AgentBehaviour
{
public:
	AgentBehaviour(){}
	virtual ~AgentBehaviour(){}
	
	bool operator<(AgentBehaviour& c){if(this->time<c.time)return true; else return false;}

	int time;
	std::string behaviour;
};


#endif  //_SCHEDULERELEMENT_H
