//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RandomSelector.h
//  @ Date : 22/07/2008
//  @ Author : 
//
//


#if !defined(_RANDOMSELECTOR_H)
#define _RANDOMSELECTOR_H

#include "Selector.h"
#include "RandomGen.h"
#include "CentralClock.h"


class RandomSelector : public Selector {
public:
	RandomSelector();
	RandomSelector(std::string name, CentralClock *pc);
	~RandomSelector();
	virtual std::string retrieveSignal();	
	int RandomSelector::GetRandomIndex(std::vector<float> *perVec);
	//void RandomSelector::SetPercentage(float percentage);

	RandomGen *randgen;

};

#endif  //_RANDOMSELECTOR_H
