//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StrictPrioritySelector.h
//  @ Date : 22/07/2008
//  @ Author : 
//
//


#if !defined(_STRICTPRIORITYSELECTOR_H)
#define _STRICTPRIORITYSELECTOR_H

#include "Selector.h"
#include "CentralClock.h"


class StrictPrioritySelector : public Selector {
public:
	StrictPrioritySelector();
	StrictPrioritySelector(std::string name, CentralClock *pc);
	~StrictPrioritySelector();
	virtual std::string retrieveSignal();
	//void StrictPrioritySelector::SetPercentage(float per);
	FILE *fid;

	std::vector<float> percentageVec; 
};

#endif  //_STRICTPRIORITYSELECTOR_H
