/*
 * ParticipantControlGUI.java
 *
 * Created on 9. Juli 2009, 17:09
 */

package eu.semaine.components.control;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.BevelBorder;

/**
 *
 * @author  marc
 */
public class ParticipantControlGUI extends javax.swing.JFrame {
    public static final String OBADIAH = "Obadiah";
    public static final String POPPY = "Poppy";
    public static final String PRUDENCE = "Prudence";
    public static final String SPIKE = "Spike";
    public static final String LABEL_USERPRESENT = "User is present.";
    public static final String LABEL_USERNOTPRESENT = "User is currently NOT present.";
    public static final String BUTTON_USERPRESENT = "User leaving";
    public static final String BUTTON_USERNOTPRESENT = "User arrives";
    
    private ParticipantControl component;
    
    /** Creates new form ParticipantControlGUI */
    public ParticipantControlGUI(ParticipantControl component) {
        this.component = component;
        initComponents();
        updateWhoIsPresent();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bToggleUser = new javax.swing.JButton();
        lUserPresent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bSpike = new javax.swing.JButton();
        bPoppy = new javax.swing.JButton();
        bPrudence = new javax.swing.JButton();
        bObadiah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Participant Control GUI");
        bToggleUser.setText("User arrives");
        bToggleUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToggleUserActionPerformed(evt);
            }
        });

        lUserPresent.setText("User is NOT present");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dialogue Partner:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        bSpike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Spike-100.jpg")));
        bSpike.setText("Spike");
        bSpike.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSpike.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSpike.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSpike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSpikeActionPerformed(evt);
            }
        });

        bPoppy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Poppy-100.jpg")));
        bPoppy.setText("Poppy");
        bPoppy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPoppy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPoppy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPoppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPoppyActionPerformed(evt);
            }
        });

        bPrudence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Prudence-100.jpg")));
        bPrudence.setText("Prudence");
        bPrudence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPrudence.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPrudence.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPrudence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrudenceActionPerformed(evt);
            }
        });

        bObadiah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Obadiah-100.jpg")));
        bObadiah.setText("Obadiah");
        bObadiah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bObadiah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bObadiah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bObadiah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bObadiahActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(bObadiah)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bPrudence))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(bSpike)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bPoppy)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bSpike)
                    .add(bPoppy))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bObadiah)
                    .add(bPrudence))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(92, 92, 92)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lUserPresent)
                            .add(bToggleUser))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lUserPresent)
                .add(5, 5, 5)
                .add(bToggleUser)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bObadiahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bObadiahActionPerformed
        component.setCurrentCharacter(OBADIAH);
    }//GEN-LAST:event_bObadiahActionPerformed

    private void bPoppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPoppyActionPerformed
        component.setCurrentCharacter(POPPY);
    }//GEN-LAST:event_bPoppyActionPerformed

    private void bSpikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpikeActionPerformed
        component.setCurrentCharacter(SPIKE);
    }//GEN-LAST:event_bSpikeActionPerformed

    private void bPrudenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrudenceActionPerformed
        component.setCurrentCharacter(PRUDENCE);
    }//GEN-LAST:event_bPrudenceActionPerformed

    private void bToggleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToggleUserActionPerformed
        boolean current = component.isUserPresent();
        component.setUserPresent(!current);
    }//GEN-LAST:event_bToggleUserActionPerformed
    

    public void updateWhoIsPresent()
    {
        boolean userPresent = component.isUserPresent();
        if (userPresent) {
            lUserPresent.setText(LABEL_USERPRESENT);
            bToggleUser.setText(BUTTON_USERPRESENT);
        } else {
            lUserPresent.setText(LABEL_USERNOTPRESENT);
            bToggleUser.setText(BUTTON_USERNOTPRESENT);
        }
        String character = component.getCurrentCharacter();
        if (OBADIAH.equals(character)) {
            markCharacter(bObadiah);
        } else {
            unmarkCharacter(bObadiah);
        }
        if (POPPY.equals(character)) {
            markCharacter(bPoppy);
        } else {
            unmarkCharacter(bPoppy);
        }
        if (PRUDENCE.equals(character)) {
            markCharacter(bPrudence);
        } else {
            unmarkCharacter(bPrudence);
        }
        if (SPIKE.equals(character)) {
            markCharacter(bSpike);
        } else {
            unmarkCharacter(bSpike);
        }
    }
    
    private void markCharacter(JButton charButton)
    {
        charButton.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
    }
    
    private void unmarkCharacter(JButton charButton)
    {
        charButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bObadiah;
    private javax.swing.JButton bPoppy;
    private javax.swing.JButton bPrudence;
    private javax.swing.JButton bSpike;
    private javax.swing.JButton bToggleUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lUserPresent;
    // End of variables declaration//GEN-END:variables
    
}
