/*
 * ParticipantControlGUI.java
 *
 * Created on 9. Juli 2009, 17:09
 */

package eu.semaine.components.control;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.BevelBorder;

/**
 *
 * @author  marc
 */
public class ParticipantControlGUI extends javax.swing.JFrame {
    // Characters
	public static final String OBADIAH = "Obadiah";
    public static final String POPPY = "Poppy";
    public static final String PRUDENCE = "Prudence";
    public static final String SPIKE = "Spike";
    public static final String MODERATOR = "Greta";
    // Dialog contexts
    public static final String ANNOUNCE = "AnnounceNextCharacter";
    public static final String INTRO = "Introduction";
    public static final String QUESTIONS1 = "Questions1";
    public static final String QUESTIONS2 = "Questions2";
    public static final String QUESTIONS3 = "Questions3";
    public static final String QUESTIONS4 = "Questions4";
    
    
    public static final String LABEL_USERPRESENT = "User is present.";
    public static final String LABEL_USERNOTPRESENT = "User is currently NOT present.";
    public static final String BUTTON_USERPRESENT = "User leaving";
    public static final String BUTTON_USERNOTPRESENT = "User arrives";
    
    private ParticipantControl component;
    
    /** Creates new form ParticipantControlGUI */
    public ParticipantControlGUI(ParticipantControl component) {
        this.component = component;
        initComponents();
        updateWhoIsPresent();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bToggleUser = new javax.swing.JButton();
        lUserPresent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bSpike = new javax.swing.JButton();
        bPoppy = new javax.swing.JButton();
        bPrudence = new javax.swing.JButton();
        bObadiah = new javax.swing.JButton();
        bIntro = new javax.swing.JButton();
        bIntroSpike = new javax.swing.JButton();
        bIntroPoppy = new javax.swing.JButton();
        bIntroPrudence = new javax.swing.JButton();
        bIntroObadiah = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        bQuestions1 = new javax.swing.JButton();
        bQuestions2 = new javax.swing.JButton();
        bQuestions3 = new javax.swing.JButton();
        bQuestions4 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Participant Control GUI");
        bToggleUser.setText("User arrives");
        bToggleUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToggleUserActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(bToggleUser, gridBagConstraints);

        lUserPresent.setText("User is NOT present");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(lUserPresent, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dialogue Partner:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        bSpike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Spike-100.jpg")));
        bSpike.setText("Spike");
        bSpike.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSpike.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSpike.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSpike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSpikeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bSpike, gridBagConstraints);

        bPoppy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Poppy-100.jpg")));
        bPoppy.setText("Poppy");
        bPoppy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPoppy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPoppy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPoppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPoppyActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bPoppy, gridBagConstraints);

        bPrudence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Prudence-100.jpg")));
        bPrudence.setText("Prudence");
        bPrudence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPrudence.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPrudence.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPrudence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrudenceActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bPrudence, gridBagConstraints);

        bObadiah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eu/semaine/components/control/Obadiah-100.jpg")));
        bObadiah.setText("Obadiah");
        bObadiah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bObadiah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bObadiah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bObadiah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bObadiahActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bObadiah, gridBagConstraints);

        bIntro.setText("Introduction");
        bIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntroActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(bIntro, gridBagConstraints);

        bIntroSpike.setText("Introduce Spike");
        bIntroSpike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntroSpikeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bIntroSpike, gridBagConstraints);

        bIntroPoppy.setText("Introduce Poppy");
        bIntroPoppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntroPoppyActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bIntroPoppy, gridBagConstraints);

        bIntroPrudence.setText("Introduce Prudence");
        bIntroPrudence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntroPrudenceActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bIntroPrudence, gridBagConstraints);

        bIntroObadiah.setText("Introduce Obadiah");
        bIntroObadiah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntroObadiahActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bIntroObadiah, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jSeparator1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluation"));
        bQuestions1.setText("1");
        bQuestions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestions1ActionPerformed(evt);
            }
        });

        jPanel2.add(bQuestions1);

        bQuestions2.setText("2");
        bQuestions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestions2ActionPerformed(evt);
            }
        });

        jPanel2.add(bQuestions2);

        bQuestions3.setText("3");
        bQuestions3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestions3ActionPerformed(evt);
            }
        });

        jPanel2.add(bQuestions3);

        bQuestions4.setText("4");
        bQuestions4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestions4ActionPerformed(evt);
            }
        });

        jPanel2.add(bQuestions4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bQuestions4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestions4ActionPerformed
    	component.setCharacterInfo(MODERATOR, null, QUESTIONS4);
    }//GEN-LAST:event_bQuestions4ActionPerformed

    private void bQuestions3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestions3ActionPerformed
    	component.setCharacterInfo(MODERATOR, null, QUESTIONS3);

    }//GEN-LAST:event_bQuestions3ActionPerformed

    private void bQuestions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestions2ActionPerformed
    	component.setCharacterInfo(MODERATOR, null, QUESTIONS2);
    }//GEN-LAST:event_bQuestions2ActionPerformed

    private void bIntroPrudenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntroPrudenceActionPerformed
    	component.setCharacterInfo(MODERATOR, PRUDENCE, ANNOUNCE);
    }//GEN-LAST:event_bIntroPrudenceActionPerformed

    private void bIntroObadiahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntroObadiahActionPerformed
    	component.setCharacterInfo(MODERATOR, OBADIAH, ANNOUNCE);
    }//GEN-LAST:event_bIntroObadiahActionPerformed

    private void bIntroPoppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntroPoppyActionPerformed
    	component.setCharacterInfo(MODERATOR, POPPY, ANNOUNCE);
    }//GEN-LAST:event_bIntroPoppyActionPerformed

    private void bIntroSpikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntroSpikeActionPerformed
    	component.setCharacterInfo(MODERATOR, SPIKE, ANNOUNCE);
    }//GEN-LAST:event_bIntroSpikeActionPerformed

    private void bQuestions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestions1ActionPerformed
    	component.setCharacterInfo(MODERATOR, null, QUESTIONS1);
    }//GEN-LAST:event_bQuestions1ActionPerformed

    private void bIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntroActionPerformed
    	component.setCharacterInfo(MODERATOR, null, INTRO);
    }//GEN-LAST:event_bIntroActionPerformed

    private void bObadiahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bObadiahActionPerformed
        component.setCurrentCharacter(OBADIAH);
    }//GEN-LAST:event_bObadiahActionPerformed

    private void bPoppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPoppyActionPerformed
        component.setCurrentCharacter(POPPY);
    }//GEN-LAST:event_bPoppyActionPerformed

    private void bSpikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpikeActionPerformed
        component.setCurrentCharacter(SPIKE);
    }//GEN-LAST:event_bSpikeActionPerformed

    private void bPrudenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrudenceActionPerformed
        component.setCurrentCharacter(PRUDENCE);
    }//GEN-LAST:event_bPrudenceActionPerformed

    private void bToggleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToggleUserActionPerformed
        boolean current = component.isUserPresent();
        component.setUserPresent(!current);
    }//GEN-LAST:event_bToggleUserActionPerformed
    

    public void updateWhoIsPresent()
    {
        boolean userPresent = component.isUserPresent();
        if (userPresent) {
            lUserPresent.setText(LABEL_USERPRESENT);
            bToggleUser.setText(BUTTON_USERPRESENT);
        } else {
            lUserPresent.setText(LABEL_USERNOTPRESENT);
            bToggleUser.setText(BUTTON_USERNOTPRESENT);
        }
        String character = component.getCurrentCharacter();
        if (OBADIAH.equals(character)) {
            markCharacter(bObadiah);
        } else if (POPPY.equals(character)) {
            markCharacter(bPoppy);
        } else if (PRUDENCE.equals(character)) {
            markCharacter(bPrudence);
        } else if (SPIKE.equals(character)) {
            markCharacter(bSpike);
        } else if (MODERATOR.equals(character)) {
        	String dialogContext = component.getDialogContext();
        	if (INTRO.equals(dialogContext) || dialogContext == null) {
        		markCharacter(bIntro);
        	} else if (QUESTIONS1.equals(dialogContext)) {
        		markCharacter(bQuestions1);
        	} else if (QUESTIONS2.equals(dialogContext)) {
        		markCharacter(bQuestions2);
        	} else if (QUESTIONS3.equals(dialogContext)) {
        		markCharacter(bQuestions3);
        	} else if (QUESTIONS4.equals(dialogContext)) {
        		markCharacter(bQuestions4);
        	} else if (ANNOUNCE.equals(dialogContext)) {
            	String nextCharacter = component.getNextCharacter();
            	 if (OBADIAH.equals(nextCharacter)) {
                     markCharacter(bIntroObadiah);
                 } else if (POPPY.equals(nextCharacter)) {
                     markCharacter(bIntroPoppy);
                 } else if (PRUDENCE.equals(nextCharacter)) {
                     markCharacter(bIntroPrudence);
                 } else if (SPIKE.equals(nextCharacter)) {
                     markCharacter(bIntroSpike);
                 } else {
                 	markCharacter(null); // unknown state, unmark all
                 }
        	} else {
            	markCharacter(null); // unknown state, unmark all
        	}
        } else {
        	markCharacter(null); // unknown state, unmark all
        }
    }
    
    private void markCharacter(JButton charButton)
    {
    	JButton[] allButtons = new JButton[] {
    		bIntro, 
    		bSpike, bIntroSpike, bPoppy, bIntroPoppy,
    		bObadiah, bIntroObadiah, bPrudence, bIntroPrudence,
                bQuestions1, bQuestions2, bQuestions3, bQuestions4
    	};
    	for (JButton b : allButtons) {
    		if (b.equals(charButton)) {
    			b.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
    		} else {
    			b.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    		}
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIntro;
    private javax.swing.JButton bIntroObadiah;
    private javax.swing.JButton bIntroPoppy;
    private javax.swing.JButton bIntroPrudence;
    private javax.swing.JButton bIntroSpike;
    private javax.swing.JButton bObadiah;
    private javax.swing.JButton bPoppy;
    private javax.swing.JButton bPrudence;
    private javax.swing.JButton bQuestions1;
    private javax.swing.JButton bQuestions2;
    private javax.swing.JButton bQuestions3;
    private javax.swing.JButton bQuestions4;
    private javax.swing.JButton bSpike;
    private javax.swing.JButton bToggleUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lUserPresent;
    // End of variables declaration//GEN-END:variables
    
}
