#pragma once
// Greta Ini parameter name
#define GBP_INIT_PARAMETER_PSYDULE_HOST "PSYCLONE_HOST"
#define GBP_INIT_PARAMETER_PSYDULE_PORT "PSYCLONE_PORT"


// Greta Message Header in the Psyclone module.
#define PSYCLONE_CLOCK_MESSAGE_HEADER "Greta.Data.Clock"
#define PSYCLONE_FML_MESSAGE_HEADER "Greta.Data.FML"
#define PSYCLONE_BML_MESSAGE_HEADER "Greta.Data.BML"
#define PSYCLONE_CARACTERISATION_BASELINE_MESSAGE_HEADER "Greta.Data.Caracterise.Baseline"
#define PSYCLONE_CARACTERISATION_BQC_MESSAGE_HEADER "Greta.Data.Caracterise.BQC"
#define PSYCLONE_CARACTERISATION_MSS_MESSAGE_HEADER "Greta.Data.Caracterise.MSS"

// Greta
#define PSYCLONE_GRETA_WHITEBOARD "Greta.Whiteboard"


// Greta Module definitions

// FML to BML Module
#define GBP_MODULE_PSYCLONE_NAME "Greta.FMLtoBMLPsydule"
#define GBP_MODULE_NAME "FMLtoBMLPsydule"
#define GBP_MODULE_GBPENGINESPARAMETERSETOFSETS_NODE_NAME "parameter-set"
#define GBP_MODULE_GBPENGINESPARAMETERSET_NODE_NAME "Parameter"
#define GBP_MODULE_GBPENGINESPARAMETERSETOFSETS_ATTRIBUTE_NAME "name"
#define GBP_MODULE_GBPENGINESPARAMETERSETOFSETS_ATTRIBUTE_VALUE "value"
#define GBP_MODULE_GBPBEHAVIORQUALITYCOMPUTATION_ATTRIBUTE_NAME "name"


#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_NODE_NAME_FOR_BEHAVIORSET "behaviorset"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_NAME_FOR_BEHAVIORSET "name"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_NODE_NAME_FOR_SIGNALS "signals"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_NODE_NAME_FOR_SIGNAL "signal"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_NAME_FOR_SIGNAL "name"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_MODALITY_FOR_SIGNAL "modality"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_ID_FOR_SIGNAL "id"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_NODE_NAME_FOR_SIGNAL_ALTERNATIVE "alternative"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_NAME_FOR_SIGNAL_ALTERNATIVE "name"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_ATTRIBUTE_PROBABILITY_FOR_SIGNAL_ALTERNATIVE "probability"
#define GBP_MODULE_GBPMULTIMODALSIGNALSELECTION_NODE_NAME_FOR_RULES "rules"

